### PR TITLE
Feature/locking issue

### PR DESCRIPTION
**Pull request by jtalborough**

### CODE REVIEW

**Review by TrevorPayne — COMMENTED** [review]
Looks good for now - I'm concerned re: the watchdog - I know why you did what you did, and it was probably the best course in the short term, but I want to be able to get a difinitive subscribed component each time the watchdog checks, or it's possible we may just try to sub to things that were never subscribed and not see an issue when it happens.

**Comment by TrevorPayne** [comment]
Merging into development first!

**Comment by jtalborough** [comment]
Yeah agreed...there is room for improvement. Stop the bleeding then sew the wound.

**Review by jkdevito — APPROVED** [review]
Approving PR based on comments provided.

**Pull request merged**
